"""Project-wide constants for the Gomoku application."""

BOARD_SIZE = 15
GRID_SPACING = 40
MARGIN = 30
STONE_RADIUS = 16
CANVAS_SIZE = MARGIN * 2 + GRID_SPACING * (BOARD_SIZE - 1)
STAR_POINTS = ((3, 3), (3, 11), (7, 7), (11, 3), (11, 11))
STAR_POINT_RADIUS = 4

WINDOW_TITLE = "Gomoku"
CANVAS_BG_COLOR = "#D8B26E"
GRID_COLOR = "#2F2F2F"
BLACK_STONE_COLOR = "#111111"
WHITE_STONE_COLOR = "#F6F6F6"
HOVER_FILL_COLOR = "#EED39A"
HOVER_OUTLINE_COLOR = "#C29649"
HOVER_RADIUS = 14
HOVER_GHOST_BLACK_FILL = "#2A2A2A"
HOVER_GHOST_BLACK_OUTLINE = "#555555"
HOVER_GHOST_WHITE_FILL = "#F5F5F5"
HOVER_GHOST_WHITE_OUTLINE = "#B8B8B8"
HOVER_GHOST_STIPPLE = "gray25"
HOVER_GHOST_RADIUS = STONE_RADIUS - 1
LAST_MOVE_MARK_RADIUS = 4
LAST_MOVE_MARK_BLACK_ON_WHITE = "#111111"
LAST_MOVE_MARK_WHITE_ON_BLACK = "#FAFAFA"
WIN_HIGHLIGHT_COLOR = "#F4D03F"
WIN_HIGHLIGHT_WIDTH = 2
CONTROL_BG_COLOR = "#F4EFE2"
STATUS_BG_COLOR = "#FBF8EE"
STATUS_BORDER_COLOR = "#D8CCAA"
UI_FONT_FAMILY = "Segoe UI"
UI_FONT_SIZE = 10
STATUS_MAX_CHARS = 48
STATUS_LABEL_WIDTH = 42
WINDOW_EXTRA_WIDTH = 0
WINDOW_EXTRA_HEIGHT = 0

STATUS_READY = "Current player: Black"
STATUS_WIN_BLACK = "Black wins!"
STATUS_WIN_WHITE = "White wins!"
STATUS_DRAW = "Draw game."
STATUS_AI_THINKING = "AI is thinking..."
STATUS_WAIT_AI = "Please wait: AI is thinking..."

MODE_HUMAN_VS_HUMAN = "Human vs Human"
MODE_HUMAN_VS_AI = "Human vs AI"
